apiVersion: v1
kind: Service
metadata:
  name: react-app
  namespace: argocd-poc-application
spec:
  selector:
    app: cubbit-react-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000